---
title: "NATURGREEN paper tables & figure (appendix)"
author: "Michael D Garber"
date: '2022-05-24'
#always_allow_html: true
#note word doesn't seem to render unless I render the whole site ()rmarkdown::render_site(encoding = 'UTF-8').
#Comment October 13, 2022: This no longer lines up
#Comment Nov 7, 2022: I'm going to revise so it lines up.
#February 3rd, 2023: this is old, but has lots of useful code, so don't put it in
#old folder just yet.
#I'm going to copy the figures to a normal R script, but
#I'm still going to use markdown for tables. Delete everything else, though.
output:
  bookdown::word_document2:
    toc: true 
---

# Supplementary tables


## Table 1: Description of scenarios (area, pop affecteds)
```{r,  eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(mapview)
library(sf)
setwd(here("data-processed"))
load("hia_all_over_ndvi_over_equity_est_boot.RData")
load("hia_all_over_ndvi_by_equity_est_boot.RData")
load("lookup_scenario_sort_order.RData") #to get it to sort how I want
load("lookup_scenario_main_text.RData") #to restrict to those in the main text if necessary
load("lookup_scenario_num.RData")
load("lookup_scenario_label.RData")
hia_all_over_ndvi_over_equity_est_boot %>% 
  bind_rows(hia_all_over_ndvi_by_equity_est_boot) %>% 
  arrange(scenario_sort_order) %>% 
  left_join(lookup_scenario_main_text, by = c("scenario", "scenario_sub")) %>% 
#  filter(scenario_main_text==1) %>% #remove from appendix but include in main-text tables
  left_join(lookup_scenario_num , by = c("scenario", "scenario_sub")) %>% #add this for presentation
  left_join(lookup_scenario_label, by=  c("scenario", "scenario_sub")) %>% #add better scenario labels
  #Create concatenated version of estimates + confidence intervals in one cell
  #I learned about formatC, which I have never used before 
  #https://stackoverflow.com/questions/3443687/formatting-decimal-places-in-r
  mutate(
    area_mi2_bg_int_tx_conc = paste0(
      as.character(formatC(area_mi2_bg_int_tx_med,digits=1, format = "f")),
      " (", 
      as.character(formatC(area_mi2_bg_int_tx_min,digits=1, format = "f")),
      ", ",
      as.character(formatC(area_mi2_bg_int_tx_max,digits=1, format="f")),
      ")")
    ,
    area_mi2_bg_int_res_conc = paste0(
      as.character(formatC(area_mi2_bg_int_res_med,digits=1, format = "f")),
      " (", 
      as.character(formatC(area_mi2_bg_int_res_min,digits=1, format = "f")),
      ", ",
      as.character(formatC(area_mi2_bg_int_res_max,digits=1, format="f")),
      ")")
    ,
    area_prop_tx_res_conc = paste0(
      as.character(formatC(area_prop_tx_res_med,digits=2, format = "f")),
      " (", 
      as.character(formatC(area_prop_tx_res_min,digits=2, format = "f")),
      ", ",
      as.character(formatC(area_prop_tx_res_max,digits=2, format="f")),
      ")"),
    #here, use big.mark to add a comma.
    pop_affected_conc =  paste0(
        as.character(formatC(pop_affected_med,digits=0, format = "f", big.mark=",")),
        " (", 
        as.character(formatC(pop_affected_ll,digits=0, format = "f", big.mark=",")),
        "; ", #using a semi-colon as a separator instead to avoid confusion with comma
        #for every thousand.
        as.character(formatC(pop_affected_ul,digits=0, format="f", big.mark=",")),
        ")")
  ) %>% 
  dplyr::select(
    scenario_num,
  scenario_label, 
    scenario_sub,
  #  scenario_sub, #not presenting sub-scenarios in the main text table
    starts_with("equity_nbhd_denver_tertile"),
    ends_with("_conc") #this picks up all the variables you just created with formatC
  ) %>%
  ungroup() %>% 
  knitr::kable(
    caption = "The cumulative area of the treatment, its corresponding residential buffer, and the population affected",
    booktabs = TRUE,
    format.args = list(big.mark = ","),
#    digits = c(0, 0, 0, 1, 1, 1, 1, 1, 1,2,2,2,0, 0,0),
    col.names = c(
            "Scenario num.",
      "Scenario",
      "Sub-scenario",
      "Equity Tertile",
      "Area, treatment (mi^2^), median (95% UI)",
      "Area, residential buffer (mi^2^), median (95% UI)",
      "Prop. of residential buffer treated, median (95% UI)",
      "Pop. affected, estimate (95% UI)"
      )  )
```
## Table 2: NDVI at baseline, alternative, and difference therein
```{r,  eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
setwd(here("data-processed"))
load("hia_all_over_ndvi_over_equity_est_boot.RData")
load("hia_all_over_ndvi_by_equity_est_boot.RData")
load("lookup_scenario_sort_order.RData") #to get it to sort how I want
load("lookup_scenario_main_text.RData") #to restrict to those in the main text if necessary
load("lookup_scenario_num.RData")
hia_all_over_ndvi_over_equity_est_boot %>% 
  bind_rows(hia_all_over_ndvi_by_equity_est_boot) %>% 
  arrange(scenario_sort_order) %>% 
  #filter to just the main sub-scenarios to present in the main text
  left_join(lookup_scenario_main_text, by = c("scenario", "scenario_sub")) %>% 
#  filter(scenario_main_text==1) %>% #remove from appendix but include in main-text tables
  left_join(lookup_scenario_num , by = c("scenario", "scenario_sub")) %>% #add this for presentation
  left_join(lookup_scenario_label, by=  c("scenario", "scenario_sub")) %>% #add better scenario labels
     #more concatenate
  mutate(
    
    #baseline ndvi of the treatment area 
    ndvi_mean_wt_tx_conc = paste0(
      as.character(formatC(ndvi_mean_wt_tx_med,digits=2, format = "f")),
      " (", 
      as.character(formatC(ndvi_mean_wt_tx_min,digits=2, format = "f")),
      ", ",
      as.character(formatC(ndvi_mean_wt_tx_max,digits=2, format="f")),
      ")"),
    
    #baseline NDVI of the full residential area
    ndvi_quo_conc = paste0(
      as.character(formatC(ndvi_quo_med,digits=2, format = "f")),
      " (", 
      as.character(formatC(ndvi_quo_min,digits=2, format = "f")),
      ", ",
      as.character(formatC(ndvi_quo_max,digits=2, format="f")),
      ")")
    ,
    ndvi_mean_alt_conc = paste0(
      as.character(formatC(ndvi_mean_alt_med,digits=2, format = "f")),
      " (", 
      as.character(formatC(ndvi_mean_alt_min,digits=2, format = "f")),
      ", ",
      as.character(formatC(ndvi_mean_alt_max,digits=2, format="f")),
      ")"),
    ndvi_diff_conc = paste0(
      as.character(formatC(ndvi_diff_med,digits=3, format = "f")),
      " (", 
      as.character(formatC(ndvi_diff_min,digits=3, format = "f")),
      ", ",
      as.character(formatC(ndvi_diff_max,digits=3, format="f")),
      ")")
  ) %>% 
  dplyr::select(
    scenario_num,
        scenario_label, 
        scenario_sub,

    starts_with("equity_nbhd_denver_tertile"),
    ends_with("_conc") #this picks up all the variables you just created with formatC
  ) %>% 
  knitr::kable(
    caption = "Baseline and alternative NDVI of the residential buffer and the corresponding difference",
    booktabs = TRUE,
#    format.args = list(big.mark = ","), #not necessary because we formatted in the paste0
#    digits = c(0,0,0,2,2,2,2,2,2,2,2,2,3,3,3), ##max digits after decimal. also not necessary
    col.names = c(
      "Scenario num.",
      "Scenario", 
      "Sub-scenario",
      "Equity Tertile", 
      "Baseline NDVI, treatment area, median (95% UI)",
      "Baseline NDVI, residential buffer, median (95% UI)",
      "Alternative NDVI, residential buffer, median (95% UI)",
      "Difference: NDVI, residential buffer, median (95% UI)"
      )
) 
```

## Table 3: Estimated deaths averted (total and rate per 100k) under each scenario
```{r,  eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
setwd(here("data-processed"))
load("hia_all_over_ndvi_over_equity_est_boot.RData")
load("hia_all_over_ndvi_by_equity_est_boot.RData")
load("lookup_scenario_sort_order.RData") #to get it to sort how I want
load("lookup_scenario_main_text.RData") #to restrict to those in the main text if necessary
load("lookup_scenario_num.RData")
hia_all_over_ndvi_over_equity_est_boot %>% 
  bind_rows(hia_all_over_ndvi_by_equity_est_boot) %>% 
  arrange(scenario_sort_order) %>% 
#  filter(scenario_main_text==1) %>% #remove from appendix but include in main-text tables
  left_join(lookup_scenario_main_text, by = c("scenario", "scenario_sub")) %>% 
  left_join(lookup_scenario_num , by = c("scenario", "scenario_sub")) %>% #add this for presentation
  left_join(lookup_scenario_label, by=  c("scenario", "scenario_sub")) %>% #add better scenario labels
   #more concatenate
  mutate(
    deaths_prevented_count_conc = paste0(
      as.character(formatC(deaths_prevented_count_med,digits=0, format = "f")),
      " (", 
      as.character(formatC(deaths_prevented_count_ll,digits=0, format = "f")),
      ", ",
      as.character(formatC(deaths_prevented_count_ul,digits=0, format="f")),
      ")"),
    
    deaths_prevented_per_pop_100k_conc = paste0(
      as.character(formatC(deaths_prevented_per_pop_100k_med,digits=0, format = "f")),
      " (", 
      as.character(formatC(deaths_prevented_per_pop_100k_ll,digits=0, format = "f")),
      ", ",
      as.character(formatC(deaths_prevented_per_pop_100k_ul,digits=0, format="f")),
      ")")
  ) %>% 
  dplyr::select(
    scenario_num,
    scenario_label, 
        scenario_sub,
    starts_with("equity_nbhd_denver_tertile"),
    ends_with("conc")
  ) %>% 
  knitr::kable(
    caption = "Estimated annual premature deaths prevented",
    booktabs = TRUE,
        col.names = c(
      "Scenario num.",
      "Scenario", 
      "Sub-scenario",
      "Equity Tertile", 
      "Deaths prevented, estimate (95% UI)", 
      "Deaths prevented per 100k, estimate (95% UI)"
      )
  )
```

