---
title: "Test-analysis"
author: "Michael D Garber"
date: "March 21 2022"
---

I would like this to show up on the website, but I don't want it to be included in the nav page. I want the ability to link to it, though.

Test full-screen mapview per
https://github.com/r-spatial/mapview/issues/38 and
https://bhaskarvk.github.io/leaflet.extras/reference/fullscreen.html

```{r loadpackages, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(sf)
library(mapview)
library(leaflet.extras)
```


## Test full-screen control in Mapview
```{r full-screen-test, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
setwd(here("data-processed"))
load("den_co_tract_geo.RData") 
mv  = den_co_tract_geo %>% 
  mapview(zcol = "tract_fips", layer.name = "Census Tract") 

mv@map %>% 
  addFullscreenControl()
```

```{r}
#Add full screen control to a combo mapview...multiple layers at once
mv_1 = den_co_tract_geo %>% 
  mapview(zcol = "area_mi2_tract", layer.name = "area")
mv_2 = den_co_tract_geo %>% 
  mapview(zcol = "county_fips", layer.name = "county")

mv_combo = mv_1+mv_2
mv_combo@map %>% 
  addFullscreenControl()
```

  
```


